### ISSUE TITLE
Please update repository with the latest revision.

### ISSUE THREAD

**Issue by sadiepowell** [bighuggies/mcnagg#1]
It seems like the site is dead for good but this repo is out of date with what was on the site when it died. Would it be possible for you to push the latest source code so that I can run a copy locally?

**Comment by bighuggies** [comment]
Site is still up btw at www.mcnagg.tv, just having DNS issues with the root domain (which are hopefully fixed now).

**Comment by sadiepowell** [comment]
Thanks!
